version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodata:/data/mongo

  app:
    build: .
    container_name: api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  mongodata:
    driver: local
